version: "3.8"
services:
  spring-boot:
    build: .
    container_name: spring-cache
    ports:
      - "8080:8080"
    environment:
        MYSQL_USER: burhan
        MYSQL_PASSWORD: password
        MYSQL_HOST: mysqldb
        MYSQL_PORT: 3306
        MYSQL_DATABASE: cache_db
    depends_on:
      - mysqldb
    networks:
      - cache
  mysqldb:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: cache_db
      MYSQL_USER : burhan
      MYSQL_PASSWORD : password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - cache
networks:
     cache:
      driver: bridge
  
    